export const OPTIONS_LEVEL_START = 'OPTIONS_LEVEL_START';
export const OPTIONS_BOARD_SIZE = 'OPTIONS_BOARD_SIZE';
export const OPTIONS_DALTONIEN = 'OPTIONS_DALTONIEN';
export const OPTIONS_GAME_TYPE = 'OPTIONS_GAME_TYPE';
