export const OPTIONS_LEVEL_START = 'OPTIONS_LEVEL_START';
export const OPTIONS_BOARD_SIZE = 'OPTIONS_BOARD_SIZE';
export const OPTIONS_COLOR_BLIND = 'OPTIONS_COLOR_BLIND';
export const OPTIONS_GAME_TYPE = 'OPTIONS_GAME_TYPE';
export const INDESTRUCTIBLE = 1;
export const DESTRUCTIBLE = 2;
export const NO_LINES = 3;
